"""Checkpoint assignments, one per section of the Python lessons.

Each problem has:
  prompt   markdown shown to the learner
  starter  code the learner edits (valid Python, uses `...` as the blank)
  solution reference answer
  check    asserts that pass for the solution and fail for the starter
`build.py` turns these into assignments/<id>.ipynb and assignments/solutions/<id>.ipynb
and verifies every solution passes and every starter fails its check.
"""

ASSIGNMENTS = [
    # ------------------------------------------------------------------ 1
    dict(
        id="A1-setup-and-basics", title="Checkpoint 1: Setup & Basics",
        after="03", lessons="Lessons 01 to 03",
        intro="Warm-up with built-in functions, the `math` module, naming rules and the two kinds of errors.",
        problems=[
            dict(title="Hypotenuse with `math`",
                 prompt="A right triangle has legs of length 3 and 4. Use the `math` module to store the hypotenuse in `hyp`.",
                 starter="import math\n\nhyp = ...",
                 solution="import math\n\nhyp = math.sqrt(3**2 + 4**2)",
                 check="assert hyp == 5, 'hyp should be 5.0'"),
            dict(title="Valid identifiers",
                 prompt="From `candidates`, keep only the names Python accepts as variable names. Store them in `valid` (any order).",
                 starter='candidates = ["my_var", "2fast", "_x", "class", "total$", "total2", "user-name", "Name"]\nvalid = ...',
                 solution='candidates = ["my_var", "2fast", "_x", "class", "total$", "total2", "user-name", "Name"]\nvalid = ["my_var", "_x", "total2", "Name"]',
                 check="assert sorted(valid) == ['Name', '_x', 'my_var', 'total2'], 'Remember: no leading digit, no symbols, no keywords.'"),
            dict(title="Repair the code",
                 prompt="`broken` holds a line of code with a syntax error. Put a corrected version in `fixed`.",
                 starter='broken = \'print("Hello, Python"\'\nfixed = ...',
                 solution='broken = \'print("Hello, Python"\'\nfixed = \'print("Hello, Python")\'',
                 check="compile(fixed, '<fixed>', 'exec')"),
            dict(title="Syntax or runtime?",
                 prompt="Label each snippet `\"syntax\"` (Python refuses to start) or `\"runtime\"` (it starts and then fails).",
                 starter='answers = {\n    \'print("hi"\': ...,\n    "10 / 0": ...,\n    \'int("abc")\': ...,\n    "[1, 2, 3][5]": ...,\n}',
                 solution='answers = {\n    \'print("hi"\': "syntax",\n    "10 / 0": "runtime",\n    \'int("abc")\': "runtime",\n    "[1, 2, 3][5]": "runtime",\n}',
                 check="assert list(answers.values()) == ['syntax', 'runtime', 'runtime', 'runtime']"),
            dict(title="Built-in functions",
                 prompt="Using only the built-ins `abs`, `round` and `max`, store the largest of `abs(-12)`, `round(7.6)` and `9` in `biggest`.",
                 starter="biggest = ...",
                 solution="biggest = max(abs(-12), round(7.6), 9)",
                 check="assert biggest == 12"),
        ]),
    # ------------------------------------------------------------------ 2
    dict(
        id="A2-types-strings-casting", title="Checkpoint 2: Data Types, Strings & Type Casting",
        after="10", lessons="Lessons 04 to 10",
        intro="Work with numbers, booleans, string indexing and slicing, and conversion between types.",
        problems=[
            dict(title="Slicing practice",
                 prompt="Given `s`, create `first` (first character), `last` (last character), `word1` (the word `Python`), `rev` (the whole string reversed) and `every_other` (every second character).",
                 starter='s = "Python Programming"\nfirst = ...\nlast = ...\nword1 = ...\nrev = ...\nevery_other = ...',
                 solution='s = "Python Programming"\nfirst = s[0]\nlast = s[-1]\nword1 = s[:6]\nrev = s[::-1]\nevery_other = s[::2]',
                 check="assert (first, last, word1) == ('P', 'g', 'Python')\nassert rev == 'gnimmargorP nohtyP'\nassert every_other == 'Pto rgamn'"),
            dict(title="Casting",
                 prompt="`a` and `b` are strings. Store their numeric sum in `sum_num` (an int) and their text join in `joined`.",
                 starter='a, b = "12", "30"\nsum_num = ...\njoined = ...',
                 solution='a, b = "12", "30"\nsum_num = int(a) + int(b)\njoined = a + b',
                 check="assert sum_num == 42 and isinstance(sum_num, int)\nassert joined == '1230'"),
            dict(title="Truthy or falsy?",
                 prompt="Without running `bool()`, fill `answers` with what `bool(value)` returns for each item of `values`. Then check yourself.",
                 starter='values = [0, 1, "", "a", [], [0], None]\nanswers = [..., ..., ..., ..., ..., ..., ...]',
                 solution='values = [0, 1, "", "a", [], [0], None]\nanswers = [False, True, False, True, False, True, False]',
                 check="assert answers == [bool(v) for v in values], 'Re-check which values are empty or zero.'"),
            dict(title="Complex numbers and float precision",
                 prompt="For `z = 3 + 4j` store its magnitude in `magnitude` and its conjugate in `conj`. Then set `close` to `True` if `0.1 + 0.2` equals `0.3` when rounded to 2 decimals.",
                 starter="z = 3 + 4j\nmagnitude = ...\nconj = ...\nclose = ...",
                 solution="z = 3 + 4j\nmagnitude = abs(z)\nconj = z.conjugate()\nclose = round(0.1 + 0.2, 2) == 0.3",
                 check="assert magnitude == 5.0\nassert conj == 3 - 4j\nassert close is True"),
            dict(title="Palindrome and repetition",
                 prompt="Set `is_pal` to `True` if `word` reads the same backwards (ignore case), and `line` to a string of 20 `=` characters.",
                 starter='word = "Madam"\nis_pal = ...\nline = ...',
                 solution='word = "Madam"\nis_pal = word.lower() == word.lower()[::-1]\nline = "=" * 20',
                 check="assert is_pal is True\nassert line == '=' * 20"),
        ]),
    # ------------------------------------------------------------------ 3
    dict(
        id="A3-operators-formatting", title="Checkpoint 3: Operators & String Formatting",
        after="16", lessons="Lessons 11 to 16",
        intro="Arithmetic, comparison, logic, identity, precedence and f-string formatting.",
        problems=[
            dict(title="Quotient and remainder",
                 prompt="Divide 47 by 5. Store the whole-number result in `quotient`, the leftover in `remainder`, and `2` to the power `10` in `power`.",
                 starter="quotient = ...\nremainder = ...\npower = ...",
                 solution="quotient = 47 // 5\nremainder = 47 % 5\npower = 2 ** 10",
                 check="assert (quotient, remainder, power) == (9, 2, 1024)"),
            dict(title="Predict the precedence",
                 prompt="Work out the value of `expr` **by hand** and store your prediction in `answer`. The check runs the expression for you.",
                 starter='expr = "2 + 3 * 4 ** 2 // 5 - 1"\nanswer = ...',
                 solution='expr = "2 + 3 * 4 ** 2 // 5 - 1"\nanswer = 10',
                 check="assert answer == eval(expr), 'Remember the order: **, then * and //, then + and -.'"),
            dict(title="Entry rules",
                 prompt="A visitor may enter if they are at least 18 **and** hold a ticket. Store the result in `can_enter`. Also set `has_a` to whether the letter `\"a\"` is in `\"banana\"`.",
                 starter='age = 25\nhas_ticket = True\ncan_enter = ...\nhas_a = ...',
                 solution='age = 25\nhas_ticket = True\ncan_enter = age >= 18 and has_ticket\nhas_a = "a" in "banana"',
                 check="assert can_enter is True and has_a is True"),
            dict(title="`==` versus `is`",
                 prompt="For the lists below set `eq` (same contents?), `same` (`a` and `b` are the same object?) and `same_c` (`a` and `c` are the same object?). Predict first, then verify with an expression.",
                 starter="a = [1, 2, 3]\nb = [1, 2, 3]\nc = a\neq = ...\nsame = ...\nsame_c = ...",
                 solution="a = [1, 2, 3]\nb = [1, 2, 3]\nc = a\neq = a == b\nsame = a is b\nsame_c = a is c",
                 check="assert (eq, same, same_c) == (True, False, True)"),
            dict(title="Format a table row",
                 prompt="Build `line` with an f-string so the name is left-aligned in 8 characters, followed by `|`, then the marks right-aligned in 8 characters with 2 decimals.",
                 starter='name = "Asha"\nmarks = 87.456\nline = ...',
                 solution='name = "Asha"\nmarks = 87.456\nline = f"{name:<8}|{marks:>8.2f}"',
                 check="assert line == 'Asha    |   87.46', repr(line)"),
        ]),
    # ------------------------------------------------------------------ 4
    dict(
        id="A4-conditionals-loops", title="Checkpoint 4: Conditionals & Loops",
        after="25", lessons="Lessons 17 to 25",
        intro="Decisions and repetition. You have not met functions yet, so everything here is written with plain variables.",
        problems=[
            dict(title="Grade ladder",
                 prompt="Rules: 90 or more is `A`, 80 or more is `B`, 70 or more is `C`, otherwise `D`. Loop over the marks and append each grade letter to the string `result`.",
                 starter='result = ""\nfor m in [95, 85, 72, 40]:\n    ...',
                 solution='result = ""\nfor m in [95, 85, 72, 40]:\n    if m >= 90:\n        result += "A"\n    elif m >= 80:\n        result += "B"\n    elif m >= 70:\n        result += "C"\n    else:\n        result += "D"',
                 check="assert result == 'ABCD'"),
            dict(title="FizzBuzz",
                 prompt="For 1 to 15: print-style logic, but build one string `out` with the items separated by spaces. Multiples of 3 become `Fizz`, of 5 become `Buzz`, of both `FizzBuzz`.",
                 starter='out = ""\nfor n in range(1, 16):\n    ...',
                 solution='out = ""\nfor n in range(1, 16):\n    if n % 15 == 0:\n        item = "FizzBuzz"\n    elif n % 3 == 0:\n        item = "Fizz"\n    elif n % 5 == 0:\n        item = "Buzz"\n    else:\n        item = str(n)\n    out += item + " "\nout = out.strip()',
                 check="assert out == '1 2 Fizz 4 Buzz Fizz 7 8 Fizz Buzz 11 Fizz 13 14 FizzBuzz'"),
            dict(title="Digit sum with `while`",
                 prompt="Use a `while` loop to add up the digits of `n` (2026 gives 2 + 0 + 2 + 6). Store the sum in `total`.",
                 starter="n = 2026\ntotal = 0\n# write your while loop below\n",
                 solution="n = 2026\ntotal = 0\nwhile n > 0:\n    total += n % 10\n    n //= 10",
                 check="assert total == 10"),
            dict(title="`continue` and `break`",
                 prompt="Add the numbers 1, 2, 3, ... to `total`, but skip multiples of 3 (`continue`) and stop (`break`) as soon as `total` is above 100. Keep the last number you added in `last`.",
                 starter="total = 0\nlast = None\nfor n in range(1, 100):\n    ...",
                 solution="total = 0\nlast = None\nfor n in range(1, 100):\n    if n % 3 == 0:\n        continue\n    total += n\n    last = n\n    if total > 100:\n        break",
                 check="assert (total, last) == (108, 17)"),
            dict(title="Star triangle",
                 prompt="Build `pattern` with nested loops so it holds a triangle of height 4, one row per line: `*`, `**`, `***`, `****` (separate rows with `\\n`, no trailing newline).",
                 starter='pattern = ""\nfor row in range(1, 5):\n    ...',
                 solution='pattern = ""\nfor row in range(1, 5):\n    for _ in range(row):\n        pattern += "*"\n    if row < 4:\n        pattern += "\\n"',
                 check="assert pattern == '*\\n**\\n***\\n****'"),
        ]),
    # ------------------------------------------------------------------ 5
    dict(
        id="A5-data-structures", title="Checkpoint 5: Data Structures",
        after="36", lessons="Lessons 26 to 36",
        intro="Lists, comprehensions, tuples, sets, dictionaries and string methods.",
        problems=[
            dict(title="List toolkit",
                 prompt="From `nums` create `sorted_desc` (largest first), `top3` (the three largest) and `total` (sum). Do not change `nums` itself.",
                 starter="nums = [5, 3, 8, 1, 9, 2]\nsorted_desc = ...\ntop3 = ...\ntotal = ...",
                 solution="nums = [5, 3, 8, 1, 9, 2]\nsorted_desc = sorted(nums, reverse=True)\ntop3 = sorted_desc[:3]\ntotal = sum(nums)",
                 check="assert sorted_desc == [9, 8, 5, 3, 2, 1]\nassert top3 == [9, 8, 5]\nassert total == 28\nassert nums == [5, 3, 8, 1, 9, 2]"),
            dict(title="Comprehension",
                 prompt="In one comprehension, build `even_squares`: the squares of the even numbers from 1 to 10.",
                 starter="even_squares = [...]",
                 solution="even_squares = [n * n for n in range(1, 11) if n % 2 == 0]",
                 check="assert even_squares == [4, 16, 36, 64, 100]"),
            dict(title="Tuples",
                 prompt="Swap `a` and `b` using tuple unpacking, then store how many times `2` appears in `t` in `twos`.",
                 starter="a, b = 1, 2\n...\nt = (1, 2, 2, 3, 2)\ntwos = ...",
                 solution="a, b = 1, 2\na, b = b, a\nt = (1, 2, 2, 3, 2)\ntwos = t.count(2)",
                 check="assert (a, b) == (2, 1)\nassert twos == 3"),
            dict(title="Set algebra",
                 prompt="Find `common` (in both), `only_a` (in `a` but not `b`), `everything` (in either) and `unique_count` (how many distinct values are in `dupes`).",
                 starter="a = {1, 2, 3, 4}\nb = {3, 4, 5}\ndupes = [1, 1, 2, 3, 3]\ncommon = ...\nonly_a = ...\neverything = ...\nunique_count = ...",
                 solution="a = {1, 2, 3, 4}\nb = {3, 4, 5}\ndupes = [1, 1, 2, 3, 3]\ncommon = a & b\nonly_a = a - b\neverything = a | b\nunique_count = len(set(dupes))",
                 check="assert common == {3, 4} and only_a == {1, 2}\nassert everything == {1, 2, 3, 4, 5}\nassert unique_count == 3"),
            dict(title="Word counter",
                 prompt="Build `freq`, a dictionary that maps each word of `sentence` to how many times it appears.",
                 starter='sentence = "to be or not to be"\nfreq = {}\nfor word in sentence.split():\n    ...',
                 solution='sentence = "to be or not to be"\nfreq = {}\nfor word in sentence.split():\n    freq[word] = freq.get(word, 0) + 1',
                 check="assert freq == {'to': 2, 'be': 2, 'or': 1, 'not': 1}"),
            dict(title="String methods and Caesar shift",
                 prompt="Clean `text` into `clean` (no outer spaces, lowercase, no comma). Then shift every letter of `word` one step forward in the alphabet into `shifted` using `ord()` and `chr()`.",
                 starter='text = "  Hello, World  "\nword = "abc"\nclean = ...\nshifted = ""\nfor ch in word:\n    ...',
                 solution='text = "  Hello, World  "\nword = "abc"\nclean = text.strip().lower().replace(",", "")\nshifted = ""\nfor ch in word:\n    shifted += chr(ord(ch) + 1)',
                 check="assert clean == 'hello world'\nassert shifted == 'bcd'"),
        ]),
    # ------------------------------------------------------------------ 6
    dict(
        id="A6-functions", title="Checkpoint 6: Functions & Functional Programming",
        after="44", lessons="Lessons 37 to 44",
        intro="Defining functions, flexible arguments, scope, lambdas and the map, filter, reduce trio.",
        problems=[
            dict(title="Default arguments",
                 prompt="Write `rectangle_area(w, h=1)` that returns the area. With one argument it should treat the height as 1.",
                 starter="def rectangle_area(w, h=1):\n    ...",
                 solution="def rectangle_area(w, h=1):\n    return w * h",
                 check="assert rectangle_area(4, 5) == 20\nassert rectangle_area(7) == 7"),
            dict(title="`*args` and `**kwargs`",
                 prompt="Write `add_all(*nums)` returning the sum of any number of values, and `describe(**info)` returning the pairs as `\"a=1, b=2\"` in the order given.",
                 starter="def add_all(*nums):\n    ...\n\n\ndef describe(**info):\n    ...",
                 solution='def add_all(*nums):\n    return sum(nums)\n\n\ndef describe(**info):\n    return ", ".join(f"{k}={v}" for k, v in info.items())',
                 check="assert add_all() == 0 and add_all(1, 2, 3) == 6\nassert describe(a=1, b=2) == 'a=1, b=2'"),
            dict(title="Global scope",
                 prompt="Write `increment()` that adds 1 to the global `count` each time it is called.",
                 starter="count = 0\n\n\ndef increment():\n    ...",
                 solution="count = 0\n\n\ndef increment():\n    global count\n    count += 1",
                 check="increment()\nincrement()\nassert count == 2"),
            dict(title="Functions as values",
                 prompt="Write `apply(func, value)` that calls `func` on `value` and returns the result.",
                 starter="def apply(func, value):\n    ...",
                 solution="def apply(func, value):\n    return func(value)",
                 check="assert apply(str.upper, 'abc') == 'ABC'\nassert apply(lambda x: x * 2, 4) == 8"),
            dict(title="Sort with a lambda",
                 prompt="Sort `people` by age (the second item) into `by_age` using a lambda as the key.",
                 starter='people = [("Asha", 30), ("Ravi", 25), ("Meera", 35)]\nby_age = ...',
                 solution='people = [("Asha", 30), ("Ravi", 25), ("Meera", 35)]\nby_age = sorted(people, key=lambda p: p[1])',
                 check="assert [p[0] for p in by_age] == ['Ravi', 'Asha', 'Meera']"),
            dict(title="`map`, `filter`, `reduce`",
                 prompt="From `nums` build `squares` (map), `evens` (filter), both as lists, and `product` of all the numbers 1 to 5 (reduce).",
                 starter="from functools import reduce\n\nnums = list(range(1, 11))\nsquares = ...\nevens = ...\nproduct = ...",
                 solution="from functools import reduce\n\nnums = list(range(1, 11))\nsquares = list(map(lambda n: n * n, nums))\nevens = list(filter(lambda n: n % 2 == 0, nums))\nproduct = reduce(lambda a, b: a * b, range(1, 6))",
                 check="assert squares == [1, 4, 9, 16, 25, 36, 49, 64, 81, 100]\nassert evens == [2, 4, 6, 8, 10]\nassert product == 120"),
        ]),
]
