"""Original lesson summaries and hands-on tasks, keyed by lesson number.

blurb : what a learner gets out of the lesson (1-2 sentences)
tasks : three small things to try after the code notebook (no solutions needed;
        the section assignments in assignments/ have auto-checked solutions)
"""

LESSONS = {
    "01": ("Why programming exists, what makes Python a good first language, and where it is used in the real world.",
           ["List three repetitive tasks in your own day that a program could do for you.",
            "Search for two well-known products or companies that use Python and note what for.",
            "Write down which Python feature from the video matters most for your goals, and why."]),
    "02": ("Install Python, run it from the terminal and IDLE, and set up Anaconda with Jupyter notebooks.",
           ["Start the Python shell and calculate `2 ** 10`, then exit it.",
            "Open a Jupyter notebook and run `import sys; print(sys.version)`.",
            "Save a one-line `hello.py` file and run it from the terminal."]),
    "03": ("Built-in functions, `print()` with `sep` and `end`, importing modules such as `math`, telling syntax errors from runtime errors, and the rules for naming things.",
           ["Print `2026-10-05` from the numbers 2026, 10 and 5 using a single `print()` call.",
            "Use `math` to get the square root of 144 and the floor of 7.9.",
            "Decide which of `my_var`, `2fast`, `_x`, `class`, `total$` are valid names, then test each in a cell."]),
    "04": ("How Python classifies data, why variables can change type, and why integers have no fixed size.",
           ["Run `type()` on five different values and list the types you see.",
            "Re-assign one variable to a value of another type and print `type()` after each step.",
            "Compute `2 ** 200` and confirm it is still an `int`."]),
    "05": ("The three numeric types: `int`, `float` and `complex`, including float precision surprises.",
           ["Evaluate `0.1 + 0.2 == 0.3`, then fix the comparison with `round()` or `math.isclose()`.",
            "Create `3 + 4j` and print its `real`, `imag` and `abs()`.",
            "Compare `type(10 / 2)` with `type(10 // 2)` and explain the difference."]),
    "06": ("What `True` and `False` really are, and which values Python treats as truthy or falsy.",
           ["Print `bool()` of `0`, `1`, `\"\"`, `\"0\"`, `[]`, `[0]` and `None`.",
            "Predict, then check, the value of `True + True + False`.",
            "Predict the result of `bool(\"False\")`, then run it."]),
    "07": ("Creating strings with different quotes, escape sequences, and why strings cannot be edited in place.",
           ["Create one multi-line string with triple quotes and print it.",
            "Try `s = \"cat\"; s[0] = \"b\"` and read the error message carefully.",
            "Print a Windows-style path containing backslashes and a tab character."]),
    "08": ("Picking single characters from a string with positive and negative positions.",
           ["For `\"PYTHON\"` print the first, last and middle characters using both index styles.",
            "Trigger an `IndexError` on purpose and explain the message.",
            "Which negative index points at the same character as index `2`?"]),
    "09": ("Joining and repeating strings, slicing with `start:stop`, and using a step to skip or reverse.",
           ["Slice `\"programming\"` to obtain `\"gram\"`, then print it reversed.",
            "Draw a divider of 20 `=` characters without typing them all.",
            "Check whether `\"madam\"` is a palindrome using a reversed slice."]),
    "10": ("Automatic (implicit) conversion versus explicit casting with `int()`, `float()`, `str()` and `bool()`.",
           ["Predict the type of `3 + 4.0` and `True + 1`, then verify.",
            "Convert `\"42\"` to an int and add 8; convert `3.99` to an int and note what happens to the decimals.",
            "Run `int(\"3.5\")`, read the error, and fix it."]),
    "11": ("The family of operators, and the seven arithmetic ones including floor division, modulus and power.",
           ["Use `divmod(17, 5)` and compare with `17 // 5` and `17 % 5`.",
            "Compute the average of three numbers of your choice.",
            "Evaluate `-7 // 2` and `-7 % 2` and explain why the results look odd."]),
    "12": ("Comparing numbers and strings with `==`, `!=`, `<`, `>`, `<=` and `>=`.",
           ["Compare `\"apple\" < \"banana\"` and `\"Zebra\" < \"apple\"`; explain using `ord()`.",
            "Test whether `x` lies strictly between 1 and 10 using a chained comparison.",
            "Spot and fix the bug in `if x = 5:`."]),
    "13": ("Combining conditions with `and`, `or`, `not`, updating variables with `+=` and friends, and `is` versus `==`.",
           ["Write out the truth table for `and`, `or` and `not` using a loop or by hand.",
            "Run `False and print(\"hi\")`. Does it print? Explain short-circuiting.",
            "Create two equal lists and show that `==` is `True` while `is` is `False`."]),
    "14": ("Checking membership with `in`, and working with bits using `&`, `|`, `^`, `~`, `<<` and `>>`.",
           ["Use `in` and `not in` on a string, a list and a dictionary's keys.",
            "Compute `10 & 6`, `10 | 6` and `10 ^ 6`, and confirm each with `bin()`.",
            "Use a left shift to compute `1 << 5` and explain it as multiplication."]),
    "15": ("Which operator runs first, and how Python breaks ties when precedence is equal.",
           ["Predict `2 + 3 * 4 ** 2 / 8 - 1` before running it, then add brackets to change the result.",
            "Work out `2 ** 3 ** 2` by hand and explain right-to-left associativity.",
            "Predict what `not True == False` evaluates to."]),
    "16": ("Building readable output with `%`, `.format()` and f-strings, including alignment and number formatting.",
           ["Print a two-line receipt where the item name is left-aligned in 10 characters and the price has 2 decimals.",
            "Rewrite one `.format()` call as an f-string.",
            "Format `1234567.891` as `1,234,567.89` using an f-string."]),
    "17": ("Making decisions in code with `if`, and why indentation matters in Python.",
           ["Print `Adult` only when `age >= 18`.",
            "Remove one level of indentation on purpose and read the `IndentationError`.",
            "Use an empty list inside an `if` and explain what happens."]),
    "18": ("Choosing between two paths with `else` and between many with an `elif` ladder.",
           ["Print whether a number is even or odd.",
            "Turn a marks value into a grade (A, B, C, D) using an `elif` ladder.",
            "Rewrite one `if/else` as a one-line conditional expression."]),
    "19": ("Placing an `if` inside another `if` to model decisions that depend on earlier decisions.",
           ["Decide a ticket price from age and student status using nested `if` statements.",
            "Rewrite the same logic with a single `and` condition. Which is easier to read?",
            "Check a username first and only then the password."]),
    "20": ("Practice: solving typical decision-making problems end to end.",
           ["Decide whether a year is a leap year.",
            "Find the largest of three numbers without using `max()`.",
            "Build a tiny calculator that picks `+`, `-`, `*` or `/` with `if/elif`."]),
    "21": ("Repeating work with `while`, and avoiding the classic infinite loop.",
           ["Print the numbers 1 to 10 using a `while` loop.",
            "Add up the numbers from 1 to 100.",
            "Take a loop that never ends because the counter is never updated, and fix it."]),
    "22": ("Controlling a loop from the inside: stop it with `break`, skip a round with `continue`, leave a placeholder with `pass`.",
           ["Stop a loop as soon as you meet a number divisible by 7.",
            "Print 1 to 15 but skip multiples of 3.",
            "Write an empty `if` body using `pass` and then replace it with real code."]),
    "23": ("Looping over the items of a string or list with `for`.",
           ["Count the vowels in a word by looping over its characters.",
            "Print every item of a list on its own line.",
            "Add up a list of numbers with a `for` loop instead of `sum()`."]),
    "24": ("Generating number sequences with `range(stop)`, `range(start, stop)` and `range(start, stop, step)`.",
           ["Predict the output of `range(5)`, `range(2, 10)` and `range(10, 0, -2)`, then print them as lists.",
            "Print the multiplication table of 7.",
            "Sum all even numbers up to 50 using a stepped range."]),
    "25": ("Putting one loop inside another to work with rows and columns.",
           ["Print a 5 by 5 square of stars, then a right-angled triangle.",
            "Print the multiplication tables 1 to 5 as a grid.",
            "List every pair `(i, j)` where `i < j` for numbers 0 to 3."]),
    "26": ("Why we need containers, and a map of the four built-in ones: list, tuple, set and dictionary.",
           ["Pick the best structure for: days of the week, unique visitor IDs, name-to-marks lookup, a GPS point.",
            "Write one sentence each on when order matters and when uniqueness matters.",
            "Which of the four can be changed after creation?"]),
    "27": ("Creating lists, indexing, slicing, joining, repeating and editing them.",
           ["Make a list of five numbers; practise indexing, slicing, concatenation and repetition.",
            "Change one element and delete another with `del`.",
            "Find the max, min and sum without writing a loop."]),
    "28": ("The built-in functions and list methods you will use daily, and why `b = a` is not a copy.",
           ["Use `append`, `extend`, `insert`, `remove`, `pop`, `sort` and `reverse`; note which return `None`.",
            "Show what goes wrong with `b = a`, then fix it with `a.copy()`.",
            "Sort a list of words ignoring case with `key=str.lower`."]),
    "29": ("Building a list in one readable line with comprehensions, including conditions.",
           ["Create the squares of 1 to 10 with a comprehension.",
            "Keep only the even numbers from a list with a comprehension.",
            "Build a 3 by 3 grid using a nested comprehension."]),
    "30": ("Tuples: ordered, fixed collections, and how unpacking works.",
           ["Compare `(5)` and `(5,)` and explain the difference.",
            "Unpack a three-item tuple into three variables.",
            "Try to change a tuple, read the error, and work around it using a list."]),
    "31": ("The few tuple methods, and handy tricks such as swapping values.",
           ["Use `count()` and `index()` on a tuple.",
            "Join two tuples into one.",
            "Swap two variables in one line using tuple unpacking."]),
    "32": ("Sets: unordered collections of unique items, and why they are fast for membership checks.",
           ["Remove duplicates from a list using a set.",
            "Show that a set has no order and cannot be indexed.",
            "Create an empty set and explain why `{}` does not work."]),
    "33": ("Set algebra: union, intersection, difference, subset checks, and safe ways to add or remove.",
           ["Given two sets of students, find who is in both, in either, and in only one.",
            "Test whether one set is a subset of another.",
            "Compare `remove()` and `discard()` on a missing item."]),
    "34": ("Dictionaries: key-value pairs for fast lookup by name instead of by position.",
           ["Create a dictionary of names and marks; read a value with `[]` and with `.get()`.",
            "Add, update and delete a key.",
            "Loop over keys, values and items separately."]),
    "35": ("Everyday dictionary methods and patterns such as counting and merging.",
           ["Count how often each letter occurs in a word using a dictionary.",
            "Merge two dictionaries with `update()` and with `|`.",
            "Use `.get(key, default)` and `.pop()` and describe what each returns."]),
    "36": ("Characters as numbers with `ord()` and `chr()`, plus the string methods used to clean and search text.",
           ["Shift each letter of `\"abc\"` by one using `ord()` and `chr()`.",
            "Clean `\"  Hello, World  \"` using `strip`, `lower` and `replace`; then `split` and `join` it.",
            "Test strings with `isdigit()`, `isalpha()` and `startswith()`."]),
    "37": ("What a function is, why we write them, and how to call one.",
           ["Write `greet(name)` that prints a greeting and call it twice.",
            "Call a function that has no `return` and print its result. What do you get?",
            "Write a function that returns the area of a rectangle."]),
    "38": ("Defining functions properly: parameters, return values, void functions and docstrings.",
           ["Compare a function that prints a value with one that returns it; use both inside an expression.",
            "Return two values from one function and unpack them.",
            "Add a docstring and read it with `help()`."]),
    "39": ("Passing values by position and giving parameters default values.",
           ["Swap the order of two positional arguments and watch the result change.",
            "Write `power(base, exp=2)` and call it with one and two arguments.",
            "Challenge: find out why `def f(x, items=[])` is risky."]),
    "40": ("Accepting any number of arguments with `*args` and any number of named ones with `**kwargs`.",
           ["Write a function that sums any number of numbers.",
            "Write a function that prints every `key=value` it receives.",
            "Call a function by unpacking a list with `*` and a dictionary with `**`."]),
    "41": ("Where a variable lives: local, global, and what happens when the names clash.",
           ["Trigger an `UnboundLocalError` and fix it with `global`; then fix it again using `return`.",
            "Create a local variable that has the same name as a global one and observe both.",
            "Explain the order Python searches names (local, enclosing, global, built-in)."]),
    "42": ("Functions are values: store them, pass them around and return them.",
           ["Assign a function to another variable and call it through that name.",
            "Write a function that takes another function as an argument and applies it.",
            "Store `+`, `-`, `*`, `/` functions in a dictionary and use it as a calculator."]),
    "43": ("Short anonymous functions with `lambda`, and when not to use them.",
           ["Write a lambda that squares a number.",
            "Write a lambda that takes two arguments and returns the larger one.",
            "Sort a list of `(name, age)` tuples by age using a lambda as the key."]),
    "44": ("Transforming, filtering and combining sequences with `map()`, `filter()` and `reduce()`.",
           ["Use `map()` to convert a list of numeric strings to integers.",
            "Use `filter()` to keep only the even numbers.",
            "Use `reduce()` from `functools` to multiply the numbers 1 to 5."]),
}

BONUS = {
    "error-handling": "Catching and handling exceptions with `try`, `except`, `else` and `finally`, plus a tour of the built-in exception types.",
    "oop": "Classes and objects, encapsulation, abstraction, inheritance, polymorphism and operator overloading, with practice programs.",
}
